[project]
name = "v2-write-up"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "manim>=0.19.1",
    "schemdraw",
    "manim-voiceover",
    "setuptools",
]
